# Generated by Django 5.0 on 2023-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagePath',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
