# Generated by Django 5.0 on 2023-12-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_imagepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imagePath',
            new_name='image',
        ),
    ]
